routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tipos', 'TipoController');

Route::resource('permisos', 'PermisoController');

Route::resource('departamentos', 'DepartamentoController');

Route::resource('funcionarios', 'FuncionarioController');

Route::resource('divisions','DivisionController');

Auth::routes();

#Para hacer los Selects dependientes
Route::get('consulta/departamentos/{id}', 'PermisoController@getDepartamentos');

Route::get('consulta/funcionarios/{id}', 'PermisoController@getFuncionarios');


Route::get('change', 'PermisoController@changeStatus');

#Route::get('/home', 'HomeController@index');

Route::get('/home', [
		'uses' => 'HomeController@index',
		'as'   => 'home'
		 ]);



Route::get('permisos/buscar', [
		'uses' => 'PermisoController@buscar',
		'as'   => 'permisos.buscar'
		 ]);

#Route::get('permisos/buscar', 'PermisoController@buscar');

Route::get('resultado', [
		'uses' => 'PermisoController@resultado',
		'as'   => 'resultado'
		  ]);

Route::get('historial', [
		'uses' => 'PermisoController@historial',
		'as'   => 'historial'
		  ]);


Route::get('permisos/pdf/{id}',
	[
		'uses' => 'PermisoController@pdf',
		'as' => 'permisos.pdf'
	]
	);

Route::get('permisos/pdf2/{id}',
	[
		'uses' => 'PermisoController@pdf2',
		'as' => 'permisos.pdf2'
	]
	);


Route::get('pdf3', 'PermisoController@pdf3');

Route::get('pdf4', 'PermisoController@pdf4');

//Route::get('consulta', 'PermisoController@consulta');

Route::get('consulta', 'PermisoController@consulta');

Route::get('historial', 'PermisoController@historial');


Route::group(['middleware'=>['rol']], function(){

Route::get('rol',function(){
	return('/');
	});
});

resources/views/elements/errors.blade.php
@if (count($errors) > 0)
<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h5 class="center">
    <b>Error:</b>
  </h5>
    <ul>
      @foreach ($errors->all() as $error)
        <li class="center">
          <i class="fa fa-exclamation-circle"></i>
          <strong>{{ $error }}</strong>
        </li>
      @endforeach
    </ul>
</div>
@endif

resources/views/elements/message.blade.php
<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong> {{\Session::get('message')}} </strong>
</div>

resources/views/elements/modal.blade.php
<div class="modal" id="confirm" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:rgb(244, 214, 16)">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <h3 class="modal-title text-center">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Advertencia
                </h3>
            </div>
            <div class="modal-body">
                <h4 class="text-center">¿Seguro de Eliminar Este Registro?</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Eliminar</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

resources/views/elements/navbar.blade.php
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      @if(auth::User()->rol == 1)
      
      <a class="navbar-brand" href="{{route('home')}}">  <i class="fa fa-hourglass-half" aria-hidden="true"></i> SIREP</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">

      
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">  <i class="fa fa-calendar-plus-o fa-1x"></i> Permisos<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">

          <li><a href="{{route('permisos.create')}}"><b><i class="fa fa-plus" aria-hidden="true"></i>Crear</b></a></li>

            <li><a  href="{{route('permisos.index')}}"><b><i class="fa fa-clipboard" aria-hidden="true" fa-1x></i>Listado</b></a></li>

            <li><a href="{{route('tipos.index')}}"><b><i class="fa fa-file-text-o" aria-hidden="true" fa-1x></i>Tipos</b></a></li>
            
          </ul>
        </li>

        

        <li>
          <a href="{{route('funcionarios.index')}}"><i class="fa fa-users fa-1x"></i> Funcionario</a>
        </li>

        <li>
          <a href="{{route('divisions.index')}}"><i class="fa fa-sitemap fa-1x" aria-hidden="true"></i> Divisiones</a>
        </li>

        <li>
          <a href="{{route('departamentos.index')}}"><i class="fa fa-cubes fa-1x" aria-hidden="true"></i>  Departamentos</a>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">  <i class="fa fa-search fa-1x"></i> Consultas<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">

          <li>
          <a href="{{route('resultado')}}"><i class="fa fa-user-o" aria-hidden="true"></i>  Funcionario</a>
        </li>
          <li>
          <a href="{{Url('historial')}}"><i class="fa fa-clock-o fa-1x" aria-hidden="true"></i> Historial</a>
        </li>

        <li>
          <a href="{{Url('consulta')}}"><i class="fa fa-search fa-1x" aria-hidden="true"></i> Consulta General</a>
        </li>

      </ul>
      </li>
       </ul>

        <ul class="nav navbar-nav navbar-right">


                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Ingresar</a></li>
                            <li><a href="{{ url('/register') }}">Registrate</a></li>
                        @else

                             @if ($activo >=1)
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span><span class="badge" style="background-color: red; vertical-align: top;"><i class="fa fa-info-circle fa-1x" aria-hidden="true"></i></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                      <a  href="{{route('permisos.index')}}">
                                      <p class="text-center text-info"><b> Permisos Activos: {{$activo}} </b></p></a>
                                    </li>
                                    
                                </ul>
                            </li>

                                @else


                                <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-globe"></span>
                                </a>

                                @endif

                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">

                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a class="btn btn-danger" href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                           <i class="fa fa-sign-out"></i> Cerrar Sesion
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
        
      @else
      
      <a class="navbar-brand" href="{{route('home')}}">  <i class="fa fa-hourglass-half" aria-hidden="true"></i> SIREP</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">

      
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">  <i class="fa fa-calendar-plus-o fa-1x"></i> Permisos<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">

          <li><a  href="{{route('permisos.create')}}"><b><i class="fa fa-plus" aria-hidden="true"></i>Crear</b></a></li>
                       
          </ul>
        </li>

        <li>
          <a href="{{route('resultado')}}"><i class="fa fa-clock-o fa-1x" aria-hidden="true"></i> Historial</a>
        </li>
        </ul>
         <ul class="nav navbar-nav navbar-right">


                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Ingresar</a></li>
                            <li><a href="{{ url('/register') }}">Registrate</a></li>
                        @else
                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a class="btn btn-danger" href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                           <i class="fa fa-sign-out"></i> Cerrar Sesion
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
        @endif


    </div>
  </div>
</nav>