routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tipos', 'TipoController');

Route::resource('permisos', 'PermisoController');

Route::resource('departamentos', 'DepartamentoController');

Route::resource('funcionarios', 'FuncionarioController');

Route::resource('divisions','DivisionController');

Auth::routes();

#Para hacer los Selects dependientes
Route::get('consulta/departamentos/{id}', 'PermisoController@getDepartamentos');

Route::get('consulta/funcionarios/{id}', 'PermisoController@getFuncionarios');


Route::get('change', 'PermisoController@changeStatus');

#Route::get('/home', 'HomeController@index');

Route::get('/home', [
		'uses' => 'HomeController@index',
		'as'   => 'home'
		 ]);



Route::get('permisos/buscar', [
		'uses' => 'PermisoController@buscar',
		'as'   => 'permisos.buscar'
		 ]);

#Route::get('permisos/buscar', 'PermisoController@buscar');

Route::get('resultado', [
		'uses' => 'PermisoController@resultado',
		'as'   => 'resultado'
		  ]);

Route::get('historial', [
		'uses' => 'PermisoController@historial',
		'as'   => 'historial'
		  ]);


Route::get('permisos/pdf/{id}',
	[
		'uses' => 'PermisoController@pdf',
		'as' => 'permisos.pdf'
	]
	);

Route::get('permisos/pdf2/{id}',
	[
		'uses' => 'PermisoController@pdf2',
		'as' => 'permisos.pdf2'
	]
	);


Route::get('pdf3', 'PermisoController@pdf3');

Route::get('pdf4', 'PermisoController@pdf4');

//Route::get('consulta', 'PermisoController@consulta');

Route::get('consulta', 'PermisoController@consulta');

Route::get('historial', 'PermisoController@historial');


Route::group(['middleware'=>['rol']], function(){

Route::get('rol',function(){
	return('/');
	});
});

resources/views/historial/index.blade.php
@extends('layouts.template')
@section('title')
        Historial
@endsection
@section('content')
<div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <h3>Listado de Funcionarios</h3>
                
        </div>
</div>
<div class="row">
        <div class="col-md-12">
                <div class="table-responsive">
                        <table id="tabla" class="display" cellspacing="0" width="100%"  class="table table-striped table-condensed table-bordered table-hover" data-form="deleteForm">
                                <thead>
                                    
                                        
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th>Cargo</th>                                      
                                        
                                        <th width="176px"><p class="text-center"> Acción</p></th>
                                </thead>
                                @foreach($funcionarios as $func)
                                        <tr>
                                                
                                                
                                                <td>{{ $func->nombre }}</td>
                                                <td>{{ $func->apellido }}</td>
                                                <td>{{ $func->cargo }}</td>                                              
                                                
                                                <td>
                                                    <div class="row">
                                                    <div class="col-md-4">
                                                    <a class="btn btn-success" data-toggle="tooltip" data-placement="top" title="Ver" data-original-title="Tooltip on top" href="{{ route('funcionarios.show', $func->id)}}">
                                                        <i class="fa fa-eye"></i></a>
                                                    </div>

                                                        <div class="col-md-4 ">
                                                            <a href="{{ URL::action('FuncionarioController@edit', $func->id)}}" class="btn btn-info" data-toggle="tooltip" data-placement="top"  title="Editar" ><i class="fa fa-edit"></i></a>
                                                        </div>

                                                        <div class="col-md-4">
                                                        {!! Form::model($func, ['method' => 'delete', 'route' => ['funcionarios.destroy', $func->id], 'class' =>'form-inline form-delete']) !!}
                                                            {!! Form::hidden('id', $func->id) !!}
                                                            <button type="submit" name="delete_modal" class="btn btn-danger delete" data-toggle="tooltip" data-placement="top" title="Eliminar" data-original-title="Eliminar"><i class="fa fa-trash"></i></button>

                                                        {!! Form::close() !!}
                                                        </div>

                                                        
                                                    </div>
                                                        
                                                        
                                                </td>
                                        </tr>
                                        
                                @endforeach
                        </table>
                </div>
                
        </div>
</div>
@endsection